name: Daily Session Analysis

on:
  schedule:
    - cron: "0 6 * * *" # Run at 6 AM UTC daily
  workflow_dispatch: # Allow manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          npm install -g @continuedev/cli

      - name: Run analysis
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_PROJECT_ID: ${{ secrets.POSTHOG_PROJECT_ID }}
          POSTHOG_HOST: https://us.posthog.com
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_OWNER: "BekahHW"
          GITHUB_REPO: "siblings-write"
        run: ./posthog-continuous-ai/daily-analysis.sh