name: Daily Session Analysis

on:
  schedule:
    - cron: "0 6 * * *" # Run at 6 AM UTC daily
  workflow_dispatch: # Allow manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@v3
        with:
  # Use deploy key if available, otherwise use default token
          ssh-key: ${{ secrets.CONTINUE_API_KEY || '' }}      

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          npm install -g @continuedev/cli

      - name: Make scripts executable
        run: |
          chmod +x ./daily-analysis.sh
          chmod +x ./analyze-sessions.sh
          chmod +x ./create-github-issues.sh

      - name: Run analysis
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_PROJECT_ID: ${{ secrets.POSTHOG_PROJECT_ID }}
          POSTHOG_HOST: https://us.posthog.com
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_OWNER: "BekahHW"
          GITHUB_REPO: "siblings-write"
        run: ./posthog-continuous-ai/daily-analysis.sh