name: Daily Session Analysis

on:
  schedule:
    - cron: '0 6 * * *'  # Run at 6 AM UTC daily
  workflow_dispatch:     # Allow manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      issues: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          # Deploy key is REQUIRED for Continue CLI integration
          ssh-key: ${{ secrets.CONTINUE_DEPLOY_KEY }}
      
      - name: Set up Continue API key
        run: |
          echo "CONTINUE_API_KEY=${{ secrets.CONTINUE_API_KEY }}" >> .env
          
      - name: Set up environment
        run: |
          echo "POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }}" >> .env
          echo "POSTHOG_PROJECT_ID=${{ secrets.POSTHOG_PROJECT_ID }}" >> .env
          echo "POSTHOG_HOST=https://us.posthog.com" >> .env
          echo "GITHUB_OWNER=${{ github.repository_owner }}" >> .env
          echo "GITHUB_REPO=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> .env
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          # Install Continue CLI for AI analysis
          npm install -g @continuedev/cli
          # GitHub CLI is pre-installed on GitHub-hosted runners
          
      - name: Make scripts executable
        run: |
          chmod +x ./posthog-continuous-ai/daily-analysis.sh
          chmod +x ./posthog-continuous-ai/analyze-sessions.sh
          chmod +x ./posthog-continuous-ai/create-github-issues.sh

      - name: Run analysis and create issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./posthog-continuous-ai/daily-analysis.sh