name: PostHog Analysis Test MVP

on:
  workflow_dispatch: # Allow manual triggering for testing
  schedule:
    - cron: "0 6 * * *" # Run at 6 AM UTC daily

jobs:
  posthog-test:


















































































































































































































































































Checking Continue account authentication...
Note: cn whoami fails in GitHub Actions (non-interactive terminal)
Testing account authentication through basic agent query...
✅ Agent responded successfully
==================================
Account information from agent:
[AGENT RESPONSE ABOUT ACCOUNT]
==================================
✅ Agent appears to be associated with bekah@continue.dev or has PostHog access

