name: PostHog Analysis Test MVP

on:
  schedule:
  - cron: '00 8 28 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  posthog-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Continue CLI
        run: npm install -g @continuedev/cli@1.4.30

      - name: Test Continue CLI Installation
        env:
          CONTINUE_API_KEY: ${{ secrets.CONTINUE_API_KEY }}
        run: |
          echo "Testing Continue CLI installation..."
          if ! cn --version; then
            echo "❌ Continue CLI not found or not working"
            exit 1
          else
            echo "✅ Continue CLI version: $(cn --version)"
          fi

      - name: Validate API Key
        env:
          CONTINUE_API_KEY: ${{ secrets.CONTINUE_API_KEY }}
        run: |
          if [ -z "$CONTINUE_API_KEY" ]; then
            echo "❌ CONTINUE_API_KEY environment variable is not set"
            exit 1
          else
            echo "✅ CONTINUE_API_KEY is configured"
          fi

      - name: Verify Continue Account
        env:
          CONTINUE_API_KEY: ${{ secrets.CONTINUE_API_KEY }}
        run: |
          echo "Checking Continue account authentication..."
          
          # Create a prompt to check account identity
          cat > account_check.txt << 'EOF'
          Please tell me:
          1. What account/email are you associated with?
          2. What organization do you belong to?
          3. Can you access PostHog integrations?
          Keep response brief and factual.
          EOF
          
          echo "Checking account through agent query (30s timeout)..."
          if timeout 30s cn -p "@account_check.txt" > account_response.md 2>account_query_error.log; then
            echo "✅ Agent responded successfully"
            echo "=================================="
            echo "Account information from agent:"
            cat account_response.md
            echo "=================================="
            
            # Check if response mentions bekah@continue.dev or indicates PostHog access
            if grep -qi "bekah@continue.dev\|bekah.*continue\|posthog.*access" account_response.md; then
              echo "✅ Agent appears to be associated with bekah@continue.dev or has PostHog access"
              echo "Proceeding with PostHog tests..."
            else
              echo "⚠️  Could not confirm bekah@continue.dev association from agent response"
              echo "Response content shown above"
              echo ""
              echo "WARNING: PostHog tests may fail if not using bekah@continue.dev account"
              echo "Continuing anyway for debugging purposes..."
            fi
          else
            echo "❌ Failed to get account information through agent"
            echo "Error log:"
            cat account_query_error.log
            echo ""
            echo "WARNING: Cannot verify account - continuing anyway"
            echo "PostHog tests may fail if wrong account is being used"
          fi

      - name: Test Basic Agent Response
        env:
          CONTINUE_API_KEY: ${{ secrets.CONTINUE_API_KEY }}
        run: |
          echo "Testing basic agent response..."

          # Create a simple test prompt
          cat > test_prompt.txt << 'EOF'
          Hello! This is a test. Please respond with:
          1. Your name/identity
          2. Current timestamp
          3. Confirm you can respond
          Keep it brief.
          EOF

          echo "Prompt content:"
          cat test_prompt.txt
          echo "=================================="

          # Test with timeout
          if timeout 30s cn -p "@test_prompt.txt" > basic_response.md 2>basic_error.log; then
            echo "✅ Basic agent test SUCCESS"
            echo "Response:"
            cat basic_response.md
          else
            echo "❌ Basic agent test FAILED"
            echo "Error log:"
            cat basic_error.log
            exit 1
          fi

      - name: Test PostHog Config Loading
        env:
          CONTINUE_API_KEY: ${{ secrets.CONTINUE_API_KEY }}
        run: |
          echo "Testing PostHog config loading..."

          # Create PostHog config test prompt
          cat > posthog_config_test.txt << 'EOF'
          Hello! I'm testing if you can load the PostHog configuration.
          Please respond with:
          1. Can you access PostHog configurations?
          2. What PostHog capabilities do you have?
          3. Are you configured for PostHog analysis?
          Keep response brief.
          EOF

          echo "PostHog config test prompt:"
          cat posthog_config_test.txt
          echo "=================================="

          # Test PostHog config with timeout
          if timeout 45s cn --config continuedev/awesome-models-posthog-gh -p "@posthog_config_test.txt" > posthog_config_response.md 2>posthog_config_error.log; then
            echo "✅ PostHog config test SUCCESS"
            echo "Response:"
            cat posthog_config_response.md
          else
            echo "❌ PostHog config test FAILED"
            echo "Error log:"
            cat posthog_config_error.log
            exit 1
          fi

      - name: Test PostHog Data Connection
        env:
          CONTINUE_API_KEY: ${{ secrets.CONTINUE_API_KEY }}
        run: |
          echo "Testing PostHog data connection..." cn --config continuedev/awesome-models-posthog-gh -p "Check my PostHog analytics and create github issues based off of that."

